spring:
  main:
    web-application-type: servlet
    
  server:
    #port: 8080
    servlet:
      encoding:
        charset: UTF-8
        enabled: true
        force: true
        
    # MYSQL data source configuration. No need to explain too much.
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 2222
    hikari:
      maximum-pool-size: 2
      pool-name: java2022-dev
      register-mbeans: true

mybatis:
  # Set the xml configuration file address for mybatis.
  config-location: "classpath:mybatis-config.xml"

  # Loads all files in the 'mapper' directory (regardless of directory hierarchy) with names ending in '-mapper.xml'.
  type-aliases-package: com.fhdone.java2022.dto
  mapper-locations: classpath:mapper/*.xml