spring:
  application:
    name: june-client

  main:
    web-application-type: servlet
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
#    fetch-registry: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000 # 连接超时时间
        readTimeout: 5000   # 读超时时间
        loggerLevel: full # 日志级别
        