#server:
#  port: 8080
  
spring:
  application:
    name: august-eureka-service
    
  main:
    web-application-type: servlet
    
  server:
    #port: 8080
    servlet:
      encoding:
        charset: UTF-8
        enabled: true
        force: true
        
    # MYSQL data source configuration. No need to explain too much.
  datasource:
    demo:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
      username: root
      password: 2222
      hikari:
        maximum-pool-size: 2
        pool-name: java2022-demo-august
        register-mbeans: true
    
    test:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
      username: root
      password: 2222
      hikari:
        maximum-pool-size: 2
        pool-name: java2022-test-august
        register-mbeans: true
      
#  security:
#    user:
#      name: admin
#      password: admin
  redis:
    redisson:
      file: classpath:redisson.yml

mybatis:
  # Set the xml configuration file address for mybatis.
  config-location: "classpath:mybatis-config.xml"

  # Loads all files in the 'mapper' directory (regardless of directory hierarchy) with names ending in '-mapper.xml'.
  # type-aliases-package: com.fhdone.java2022.march.dto
  # mapper-locations: classpath:mapper/**/*.xml
  
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
#    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS   
        
elasticjob:
  # 注册中心配置
  regcenter:
    serverlists: 127.0.0.1:2181
    # ZooKeeper 的命名空间
    namespace: elastic-job-x
  # 作业配置
  jobs:
    springJob: # job的名称
      elasticJobClass: com.fhdone.java2022.august.job.SpringBootJob
      cron: 0/5 * * * * ?
      shardingTotalCount: 3
      shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou