#server:
#  port: 8080
  
spring:
  application:
    name: july-eureka-service
    
  main:
    web-application-type: servlet
    
  server:
    #port: 8080
    servlet:
      encoding:
        charset: UTF-8
        enabled: true
        force: true
        
    # MYSQL data source configuration. No need to explain too much.
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 2222
    hikari:
      maximum-pool-size: 2
      pool-name: java2022-dev
      register-mbeans: true
  
#  security:
#    user:
#      name: admin
#      password: admin
  redis:
    redisson:
      file: classpath:redisson.yml

mybatis:
  # Set the xml configuration file address for mybatis.
  config-location: "classpath:mybatis-config.xml"

  # Loads all files in the 'mapper' directory (regardless of directory hierarchy) with names ending in '-mapper.xml'.
  type-aliases-package: com.fhdone.java2022.july.dto
  mapper-locations: classpath:mapper/*.xml
  
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
#    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS      